export default {
    SIGN_IN: 'sign_in',
    SIGN_IN_ERROR: 'sign_in_error',
    SIGN_OUT: 'sign_out',
    SIGN_UP: 'sign_up',
    ERROR: 'error',
    SIGN_UP_ERROR: 'sign_up_error',
    GET_PROFILE_DATA: 'get_profile_data',
    GET_SETS_DATA: 'get_sets_data',
    GET_TOPICS_CARDS: 'get_topics_cards',
    SORT_ALPHABETICAL: 'sort_alphabetical',
    SORT_BY_LATEST: 'sort_by_latest',
    GET_CARD_DATA: 'get_card_data',
    SEND_CARD_DATA: 'send_card_data',
    GET_ALL_CARD_DATA: 'get_all_card_data',
    SEND_CATEGORY_AND_SUBCATEGORY_DATA:'send_category_and_subcategory_data',
    DELETE_CARD: 'delete_card',
    CREATE_CARD_DATA: 'create_card_data',
    SEND_CREATE_CARD_DATA: 'send_create_card_data',
    UPDATE_FIND_TIME_PASSED: 'update_find_time_passed',
    DELETE_SUBCATEGORY: 'delete_subcategory',
    UPDATE_AVATAR: 'update_avatar',
    END_TUTORIAL: 'end_tutorial',
    TUTORIAL_COMPLETED: 'tutorial_completed'
};
